// Exportar todas las funciones de servicios CRUD
export {
  createUser,
  deleteUser,
  getAllUsers,
  getPatientBookings,
  getTherapistBookings,
  getUserByEmail,
  getUserById,
  getUserBySupabaseId,
  getUsersByRole,
  updateUser,
} from "./user.service";

export {
  createLocation,
  deleteLocation,
  findNearbyLocations,
  getAllLocations,
  getLocationBookings,
  getLocationBusinessHours,
  getLocationById,
  searchLocationsByAddress,
  searchLocationsByTitle,
  updateLocation,
} from "./location.service";

export {
  createBusinessHours,
  createMultipleBusinessHours,
  deleteBusinessHours,
  deleteBusinessHoursByLocation,
  getAllBusinessHours,
  getAvailableHours,
  getBusinessHoursByDayAndLocation,
  getBusinessHoursById,
  getBusinessHoursByLocation,
  getCurrentWeekHours,
  isLocationOpen,
  updateBusinessHours,
} from "./business-hours.service";

export {
  createSpecialty,
  deleteSpecialty,
  getAllSpecialties,
  getPopularSpecialties,
  getSpecialtiesWithServices,
  getSpecialtyById,
  getSpecialtyByName,
  getSpecialtyStats,
  searchSpecialtiesByName,
  specialtyExists,
  updateSpecialty,
} from "./specialty.service";

export {
  createMultipleServices,
  createService,
  deleteService,
  deleteServicesBySpecialty,
  getAllServices,
  getCheapestServices,
  getMostExpensiveServices,
  getMostPopularServices,
  getServiceById,
  getServicesByDuration,
  getServicesByDurationRange,
  getServicesByPriceRange,
  getServicesBySpecialty,
  getServiceStats,
  getServiceStatsBySpecialty,
  searchServicesByDescription,
  serviceExists,
  updateService,
} from "./service.service";

export {
  assignTherapistToBooking,
  checkTherapistAvailability,
  checkTimeSlotAvailability,
  createBooking,
  createBookingFromForm,
  deleteBooking,
  deleteBookingsByLocation,
  deleteBookingsByPatient,
  deleteBookingsByTherapist,
  getAllBookings,
  getAvailableTimeSlots,
  getBookingById,
  getBookingsByDate,
  getBookingsByDateRange,
  getBookingsByEmail,
  getBookingsByLocation,
  getBookingsByName,
  getBookingsByPatient,
  getBookingsByPhone,
  getBookingsByTherapist,
  getBookingsByTherapistAndDate,
  getBookingsByType,
  getBookingStats,
  getBookingStatsByLocation,
  getBookingStatsByTherapist,
  getPendingBookings,
  getRecentBookings,
  mapBookingFormDataToCreateData,
  updateBooking,
  updateBookingStatus,
} from "./booking.service";

// Exportar tipos desde la carpeta types
export type {
  BookingFormData,
  CreateBookingData,
  CreateBusinessHoursData,
  CreateLocationData,
  CreateServiceData,
  CreateSpecialtyData,
  CreateUserData,
  UpdateBookingData,
  UpdateBusinessHoursData,
  UpdateLocationData,
  UpdateServiceData,
  UpdateSpecialtyData,
  UpdateUserData,
} from "@/types";
