import * as React from 'react'

import { PST_TZ, formatInTZ } from '@/lib/utils/timezone'

interface AppointmentInviteEmailProps {
  patientName: string
  patientEmail?: string
  therapistName: string
  locationAddress: string
  notes?: string
  start: Date // Fecha/hora de inicio (Date real)
  end: Date   // Fecha/hora de fin (Date real)
  googleCalendarUrl?: string
  language?: 'es' | 'en'
}

export function AppointmentInviteEmail({
  patientName,
  patientEmail,
  therapistName,
  locationAddress,
  notes,
  start,
  end,
  googleCalendarUrl,
  language = 'es',
}: AppointmentInviteEmailProps) {
  const isSpanish = language === 'es'

  const t = {
    title: isSpanish ? 'Solicitud de Cita' : 'Appointment Request',
    greeting: isSpanish ? 'Hola,' : 'Hello,',
    intro: isSpanish
      ? 'Se ha solicitado la siguiente cita:'
      : 'The following appointment has been requested:',
    patient: isSpanish ? 'Participante' : 'Participant',
    email: isSpanish ? 'Correo' : 'Email',
    therapist: isSpanish ? 'Profesional' : 'Professional',
    when: isSpanish ? 'Cuándo' : 'When',
    where: isSpanish ? 'Dónde' : 'Where',
    notesLabel: isSpanish ? 'Notas' : 'Notes',
    addToCalendar: isSpanish ? 'Añadir a Calendario' : 'Add to Calendar',
    footer: isSpanish
      ? 'Este mensaje fue generado automáticamente por el sistema de solicitudes de citas.'
      : 'This message was automatically generated by the booking system.',
  }

  const dateLine = `${formatInTZ(start, 'EEEE dd MMMM yyyy', PST_TZ)}`
  const timeLine = `${formatInTZ(start, 'hh:mm a', PST_TZ)} – ${formatInTZ(end, 'hh:mm a', PST_TZ)} (${PST_TZ})`

  return (
    <div style={{ fontFamily: 'Arial, sans-serif', maxWidth: '600px', margin: '0 auto', backgroundColor: '#ffffff' }}>
      {/* Header */}
      <div style={{ backgroundColor: '#1e40af', padding: '24px 20px', textAlign: 'center', borderTopLeftRadius: '8px', borderTopRightRadius: '8px' }}>
        <h1 style={{ color: '#ffffff', margin: 0, fontSize: '20px', fontWeight: 700 }}>{t.title}</h1>
      </div>

      {/* Body */}
      <div style={{ padding: '24px 20px' }}>
        <p style={{ fontSize: '16px', color: '#374151', margin: '0 0 16px 0' }}>{t.greeting}</p>
        <p style={{ fontSize: '14px', color: '#374151', margin: '0 0 20px 0' }}>{t.intro}</p>

        {/* Details Card */}
        <div style={{ backgroundColor: '#f8fafc', border: '1px solid #e2e8f0', borderRadius: 8, padding: 16 }}>
          <div style={{ marginBottom: 10 }}>
            <strong style={{ color: '#374151' }}>{t.patient}:</strong>
            <span style={{ color: '#374151', marginLeft: 8 }}>{patientName}</span>
          </div>
          {patientEmail && (
            <div style={{ marginBottom: 10 }}>
              <strong style={{ color: '#374151' }}>{t.email}:</strong>
              <span style={{ color: '#1e40af', marginLeft: 8 }}>
                <a href={`mailto:${patientEmail}`} style={{ color: '#1e40af', textDecoration: 'none' }}>{patientEmail}</a>
              </span>
            </div>
          )}
          <div style={{ marginBottom: 10 }}>
            <strong style={{ color: '#374151' }}>{t.therapist}:</strong>
            <span style={{ color: '#374151', marginLeft: 8 }}>{therapistName}</span>
          </div>
          <div style={{ marginBottom: 10 }}>
            <strong style={{ color: '#374151' }}>{t.when}:</strong>
            <span style={{ color: '#374151', marginLeft: 8 }}>{dateLine} · {timeLine}</span>
          </div>
          <div style={{ marginBottom: 10 }}>
            <strong style={{ color: '#374151' }}>{t.where}:</strong>
            <span style={{ color: '#374151', marginLeft: 8 }}>{locationAddress}</span>
          </div>
          {notes && (
            <div style={{ marginTop: 12 }}>
              <strong style={{ color: '#374151' }}>{t.notesLabel}:</strong>
              <p style={{ color: '#374151', margin: '6px 0 0 0', whiteSpace: 'pre-wrap' }}>{notes}</p>
            </div>
          )}
        </div>

        {googleCalendarUrl && (
          <div style={{ marginTop: 16, textAlign: 'center' }}>
            <a
              href={googleCalendarUrl}
              style={{
                display: 'inline-block',
                background: '#1e40af',
                color: '#ffffff',
                padding: '10px 16px',
                borderRadius: 6,
                textDecoration: 'none',
                fontSize: 14,
              }}
            >
              {t.addToCalendar}
            </a>
          </div>
        )}
      </div>

      {/* Footer */}
      <div style={{ backgroundColor: '#f8fafc', padding: 16, textAlign: 'center', borderBottomLeftRadius: 8, borderBottomRightRadius: 8, borderTop: '1px solid #e2e8f0' }}>
        <p style={{ color: '#6b7280', fontSize: 12, margin: 0 }}>{t.footer}</p>
      </div>
    </div>
  )
}


